# Generated by Django 2.2.5 on 2019-11-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Reg',
        ),
    ]
